
let tsv_en_ch_v4 = `potato	n	K'oteehat baabas.	The potatoes grew bigger.	Kishaalen' naʔ baabasi ʔustuubaw.	I'm going to fry the potatoes on the stove.	Yupp’ut baabasin ch'oonut'.	The skin of the potato wrinkled.	Galjin baabasam’ ʔaman.	They have a lot of potatoes.	Wantaʔ naanin baabasan.	She gave us some potatoes.	Loxtoʔ xap’li ʔilk’a baabasiw.	He poured hot water on the potatoes.			baabas	baabasi	baabasin	baabasam'	baabasan	baabasiw	
hole (general)	n	Mich k'otiʔ bokbokish ʔodbinit.	A very big hole opened up.	Diʔishtaʔ naʔ bokbokshi sheleelaw.	I made a hole in the rock.							Wumiltaʔ sheleela bokbokshiw.	He threw a rock into the hole.			bokbokish	bokbokshi	bokbokshin	bokboksham'	bokbokshan	bokbokshiw	
meat	n	Ch'ik'neʔ miʔin boʔush.	The meat is going to rot soon.	Kewshit naʔ boʔsha.	I boiled the meat.					Wantaʔ naanin boʔshan.	She gave us some meat.	Loxtoʔ xap’li ʔilk’a boʔshaw.	He poured hot water on the meat.			boʔush	boʔsha	boʔshin	boʔsham'	boʔshan	boʔshaw	
dog	n	Cheexaʔ yawaltaʔ noonoʔon.	The dog chased the man.	Yawaltaʔ noonoʔ cheexaʔan.	The man chased the dog.	Cheexaʔan k’ut' lap'taʔ nan.	The dog's tail whipped me.	Galjin cheexam’ naaʔan.	We have many dogs.			Wumiltaʔ wech'eeta cheexaw.	He threw a stick at the dog.			cheexaʔ	cheexaʔan	cheexaʔan	cheexam'	cheexan	cheexaw	
foot	n	Taxeetaxon' nim dadach'.	My feet have been aching.	Taʔashʔan' naʔ nim dadaach'i.	I'm looking at my feet.					ʔutuytaʔ cheexaʔan ʔam dadaach’an.	He pushed the dog with his foot.	Widintaʔ boshow’ ʔam dadaach’iw.	The round stone fell on his foot.			dadach'	dadaach'i	dadaach'in	dadaach'am'	dadaach'an	dadaach'iw	
hawk; chicken hawk	n	Hoyintaʔ diwdiw' sipin'.	The hawk flew above.	Yawaltaʔ k'otiʔ ch'enbay' diwdiwa.	A big bird chased the hawk.	Taʔishtaʔ ʔaman diwdiwin k’ut’a.	They saw the hawk’s tail.									diwdiw	diwdiwa	diwdiwin			diwdiwaw	
cat	n	Xishwit gaaduʔ ʔutuʔun.	The cat scratched the tree.	Yawaltaʔ cheexaʔ gaaduʔun.	The dog chased the cat.	Taxeetat gaaduʔun k’ut’.	The cat’s tail is hurting.	Galjin gaadum' Kim.	Kim has many cats.			Xayan’ shoboono gaaduw.	She will put a blanket on the cat.			gaaduʔ	gaaduʔun	gaaduʔun	gaadum'	gaadun	gaaduw	
family; cousin; relative	n	ʔoyit nim heedin Pelesnow.	My family moved to Fresno.	Taʔishtaʔ naʔ ʔam heedina denderow.	I saw his family in the store.	Mich k’ot’iʔ ʔam heedinin xoʔ.	His cousin’s house is very big.	Galjin heedinam’ ʔam namix.	Her friend has many cousins.							heedin'	heedina	heedinin	heedinam'		heedinaw	
tail	n	Goosin k'ut' yuxaʔich'.	The pig's tail is curly.	Dach'taʔ naʔ ʔam k'ut'a.	I stepped on its tail.											k'ut'	k'ut'a	k'ut'in	k'ut'am'		k'ut'aw	
fish	n	Shilit'taʔ lopis nim wakaayaw.	My fish jumped into the river.	Kuyʔulut lopso.	She salted the fish.	Mich waʔat' lopsin k’ut’.	The tail of the fish is really long.	Galjin lopsam’ ʔaman.	They have a lot of fish.	Wantaʔ noonoʔ namxa ʔam lopsan.	The man gave his friend a fish.					lopis	lopso	lopsin	lopsam'	lopsan	lopsow	
blackberry	n	Meejintaʔ k'uyuuk'ataʔ maamil'.	The blackberries were very sweet.	Goobeʔ naʔ miʔin maamila.	I'm going to pick blackberries soon.	Yupp’ut ch'oonut' maamilin.	The skin of the blackberry wrinkled.	Galjin maamilam’ ʔaman.	They have a lot of blackberries.	K'oʔtoʔ Jack nan maamilan.	Jack pelted me with a blackberry.					maamil'	maamila	maamilin	maamilam'	maamilan	maamilaw	
grey squirrel	n	Xataʔan' maw' simiiyaʔan.	The grey squirrel is eating seeds.	Maawi naʔ wanit toonan.	I gave the grey squirrel some nuts.	Taʔishtaʔ naaʔan maawin k’ut’a.	We saw the grey squirrel's tail.					Wumiltaʔ wech'eeta maawiw.	He threw a stick at the grey squirrel.			maw'	maawi	maawin			maawiw	
eight	n	Hiʔ daʔ monosh bilaasuʔ.	Here are eight plates.	Xattaʔ ʔamaʔ monoosha duldiiyaʔan.	He ate eight tortillas.											monosh	monoosha	monooshin	monoosham'	monooshan	monooshaw	
road	n	Ch'apeeyataʔ pel'.	The road was wet.	Diʔsheʔ ʔaman peeli.	They will build the road.							Shidgila naʔ bok’toʔ peeliw	I found a squirrel on the road.			pel'	peeli	peelin			peeliw	
wing; feather	n	Limeek'ataʔ ʔam saayiʔ.	Its wings became black.	Xayaataʔ saayiʔin lameesaw.	He put down the feather on the table.											saayiʔ	saayiʔin	saayiʔin			saayiw	
ground squirrel	n	Shidgil' ʔam waayit shoyxo.	The squirrel dug its hole.	Shidgila naʔ bokhil peeliw.	I found a squirrel on the road.	K'oteehat shidgilin naaway'.	The ground squirrel's cheek got bigger.					Wumiltaʔ toona shidgilaw.	He threw a nut at the ground squirrel.			shidgil'	shidgila	shidgilin		shidgilan	shidgilaw	
three	n	Hoy'nit shoopin ch'enbay' waʔlaw.	Three birds flew in the sky.	Hoyuch'taʔ naʔ shoopina ʔaabula.	I wanted three apples.											shoopin'	shoopina	shoopinin	shoopinam'	shoopinan	shoopinaw	
cottontail rabbit	n	Tishtaʔ tew' ch'ayaaxiw.	The cottontail rabbit came out of the bush.	Yawaltaʔ cheexaʔ nim teewa.	My dog chased the rabbit.	Taʔishtaʔ ʔaman teewin k’ut’a.	They saw the cottontail rabbit’s tail.									tew'	teewa	teewin		teewan	teewaw	
mountain lion	n	Gadaayit weheeshit.	The mountain lion was hungry.	Weheeshita naʔ beeletaʔ.	I fed the mountain lion.	Taʔishtaʔ naaʔan weheeshitin k’ut’a.	We saw the mountain lion's tail.									weheeshit	weheeshita	weheeshitin			weheeshitaw	
belt	n	Hiʔ woshok' mich dindinich'.	This belt is very thick.	Hech'eytaʔ naʔ woshook'o.	I tightened the belt.			Galjin woshook’am’.	He has many belts.	Wantaʔ noonoʔ namxa ʔam woshookʔon.	The man gave his friend a belt.	ʔopxit na ‘ilk’a ‘am woshook’ow.	I spilled water on his belt.			woshok'	woshook'o	woshook'in	woshook'am'	woshook'an	woshook'ow	
jackrabbit	n	Shilit'taʔ xomix.	The jackrabbit jumped.	Yawaalit kaʔyuʔ xomxi.	The coyote chased the jackrabbit.	Taʔishtaʔ naaʔan xomxin k’ut’a.	We saw the jackrabbit's tail.					Wumiltaʔ ch'edaʔhiya xomxiw.	He threw some vegetables at the jackrabbit.			xomix	xomxi	xomxin			xomxiw	
house	n	Xoʔ nim ʔooch'iy'.	My house is nearby.	Walxon' may' ʔam xoʔo.	We are passing his house.			Galjin xoʔam’.	She has many houses.			ʔaaxeʔ naʔ min xoʔow.	I’m going to stay overnight at your house.			xoʔ	xoʔo		xoʔam'	xoʔan	xoʔow	
snow	n	Miʔin ʔeeniʔ ch'aapit.	Then the snow melted.	Taʔishtaʔ ʔaman ʔeeniʔin.	They saw the snow.							Teesaʔhiʔ soplit ʔeeniw.	The lizard froze in the snow.			ʔeeniʔ	ʔeeniʔin				ʔeeniw	
tree	n	Bohloʔ miʔin galjin ʔutuʔ hew.	Many trees will soon grow here.	Halaxnit shidgil' ʔutuʔun.	The squirrel climbed the tree.	Limeek’ataʔ ch’oonut ʔutuʔun.	The skin of the tree became dark.					Taʔshit naʔ wuʔshula ʔutuw.	I saw an eagle in the tree.			ʔutuʔ	ʔutuʔun	ʔutuʔun	ʔutum'	ʔutun	ʔutuw	
bite	v	ʔach'ch'it naʔ ʔam.	I bit him just now.	ʔach'ich'taʔ cheexaʔ gaaduʔun.	The dog bit the cat.	ʔach'ich'hil cheexaʔ ʔap'ooma lagyiw.	The dog bit the ball yesterday.	ʔach'ach'ʔan' k'eenich' shidgila.	The ants are biting the squirrel.	ʔach'ich'ga ʔam!	Bite him!	Nahniʔ naʔash ʔach'ch'al mam.	It might bite you.	ʔach'ch'eʔ mam.	It is going to bite you.	ʔach'ch'it	ʔach'ich'taʔ	ʔach'ich'hil	ʔach'ach'ʔan'	ʔach'ich'ga	ʔach'ch'al	ʔach'ch'eʔ
cook	v	Gosneenot naʔ hoona.	I cooked eggs.	Gosneenotaʔ naʔ limna.	I cooked acorn drink.	Gosneenohil gayiinaʔan lagyiw.	He cooked the chicken yesterday.	Gosneenoxon' na' hach'a.	I am cooking right now.	Gosneenog gayiina'an!	Cook the chicken!	Nahniʔ naʔash gosneenol gayiinaʔan.	He might cook the chicken.	Gosneenon' ʔamaʔ hiikaw.	She is going to cook tomorrow.	gosneenot	gosneenotaʔ	gosneenohil	gosneenoxon'	gosneenog	gosneenol	gosneenon'
melt	v	ʔeeniʔ ch'apnit.	The snow melted.	Ch'aapintaʔ soopul'.	The ice melted.	Ch'aapinhil ʔeeniʔ lagyiw.	The snow melted yesterday.					Nahniʔ naʔash ch'apnal ʔeeniʔ hoy'li.	The snow might melt quickly.	ch'apneʔ ʔeeniʔ hiikaw.	The snow will melt tomorrow.	ch'apnit	ch'aapintaʔ	ch'aapinhil			ch'apnal	ch'apneʔ
big	adj	Hewethil denderow taa k'ot'iʔ noonoʔ hoy'li.	That big man walked to the store.	Taʔishtaʔ naʔ k'ot'iiʔin p'alp'alya	I saw the big pounding rock.							Loxtoʔ ʔilk’a k'ot'iw cheexaw.	He poured water on the big dog.			k'ot'iʔ	k'ot'iiʔin				k'ot'iw	
long	adj	Noʔom nim waʔat'.	My mother is tall.	Chishtaʔ ʔam waʔat'i shilshi.	She cut her long hair.							Wumiltaʔ wech'eeta nassiw wa'at'iw.	He threw a stick at the long rattlesnake.			waʔat'	waʔat'i				waʔat'iw	`;
